// AUTO-GENERATED from CK3 materials.settings — DO NOT EDIT BY HAND.
// Source:  C:\Program Files (x86)\Steam\steamapps\common\Crusader Kings III\game\gfx\map\terrain\materials.settings
// Mtime:   2026-05-04T11:31:51.0931414Z
// Sha256:  35651616c7bed3deff5d9ad43a3e5846e687752ea2e43cfcec18f44fb0ad5bf8
// Entries: 105
// Regenerate: ./TerrainLab --gen-materials

namespace Converter.Lemur.Splats;

public static class Ck3MaterialBytes
{
    public const string SourceMtimeUtc = "2026-05-04T11:31:51.0931414Z";
    public const string SourceSha256   = "35651616c7bed3deff5d9ad43a3e5846e687752ea2e43cfcec18f44fb0ad5bf8";

    public static readonly IReadOnlyDictionary<string, byte> ByName = new Dictionary<string, byte>
    {
        ["drought"] = 0,
        ["drought_cracks"] = 1,
        ["flood"] = 2,
        ["summer_grass"] = 3,
        ["winter_effect"] = 4,
        ["_debug"] = 5,
        ["beach_02"] = 6,
        ["beach_02_mediterranean"] = 7,
        ["beach_02_pebbles"] = 8,
        ["coastline_cliff_desert"] = 9,
        ["coastline_cliff_grey"] = 10,
        ["desert_01"] = 11,
        ["desert_02"] = 12,
        ["desert_cracked"] = 13,
        ["desert_flat_01"] = 14,
        ["desert_rocky"] = 15,
        ["desert_wavy_01"] = 16,
        ["desert_wavy_01_larger"] = 17,
        ["drylands_01"] = 18,
        ["drylands_01_cracked"] = 19,
        ["drylands_01_grassy"] = 20,
        ["farm_paddy_01"] = 21,
        ["farmland_01"] = 22,
        ["floodplains_01"] = 23,
        ["forest_jungle_01"] = 24,
        ["forest_leaf_01"] = 25,
        ["forest_pine_01"] = 26,
        ["forestfloor"] = 27,
        ["hills_01"] = 28,
        ["hills_01_rocks"] = 29,
        ["hills_01_rocks_medi"] = 30,
        ["hills_01_rocks_small"] = 31,
        ["india_farmlands"] = 32,
        ["medi_dry_mud"] = 33,
        ["medi_farmlands"] = 34,
        ["medi_grass_01"] = 35,
        ["medi_lumpy_grass"] = 36,
        ["medi_noisy_grass"] = 37,
        ["mud_wet_01"] = 38,
        ["northern_plains_01"] = 39,
        ["oasis"] = 40,
        ["plains_01"] = 41,
        ["plains_01_dry"] = 42,
        ["plains_01_dry_mud"] = 43,
        ["plains_01_noisy"] = 44,
        ["plains_01_rough"] = 45,
        ["snow"] = 46,
        ["steppe_bushes"] = 47,
        ["steppe_grass"] = 48,
        ["steppe_rocks"] = 49,
        ["wetlands_02"] = 50,
        ["wetlands_02_mud"] = 51,
        ["central_mountain"] = 52,
        ["central_lowlands_02"] = 53,
        ["central_lowlands_03"] = 54,
        ["gen_tropical_base"] = 55,
        ["gen_tropical_lowlands"] = 56,
        ["gen_tropical_lowlands_02"] = 57,
        ["gen_tropical_lowlands_03"] = 58,
        ["gen_tropical_hills"] = 59,
        ["gen_tropical_mountain"] = 60,
        ["gen_tropical_mountain_transition"] = 61,
        ["gen_central_base"] = 62,
        ["gen_central_lowlands"] = 63,
        ["gen_central_lowlands_02"] = 64,
        ["gen_central_lowlands_03"] = 65,
        ["gen_central_hills"] = 66,
        ["gen_central_mountain"] = 67,
        ["gen_central_mountain_transition"] = 68,
        ["gen_steppe_base"] = 69,
        ["gen_steppe_lowlands"] = 70,
        ["gen_steppe_lowlands_02"] = 71,
        ["gen_steppe_lowlands_03"] = 72,
        ["gen_steppe_hills"] = 73,
        ["gen_steppe_mountain"] = 74,
        ["gen_steppe_mountain_transition"] = 75,
        ["gen_desert_base"] = 76,
        ["gen_desert_lowlands"] = 77,
        ["gen_desert_lowlands_02"] = 78,
        ["gen_desert_lowlands_03"] = 79,
        ["gen_desert_lowlands_04"] = 80,
        ["gen_desert_hills"] = 81,
        ["gen_desert_mountain"] = 82,
        ["gen_desert_mountain_transition"] = 83,
        ["gen_drylands_base"] = 84,
        ["gen_drylands_lowlands"] = 85,
        ["gen_drylands_lowlands_02"] = 86,
        ["gen_drylands_lowlands_03"] = 87,
        ["gen_drylands_hills"] = 88,
        ["gen_drylands_mountain"] = 89,
        ["gen_drylands_mountain_transition"] = 90,
        ["gen_northern_base"] = 91,
        ["gen_northern_lowlands"] = 92,
        ["gen_northern_lowlands_02"] = 93,
        ["gen_northern_lowlands_03"] = 94,
        ["gen_northern_hills"] = 95,
        ["gen_northern_mountain"] = 96,
        ["gen_northern_mountain_transition"] = 97,
        ["gen_mediterranean_base"] = 98,
        ["gen_mediterranean_lowlands"] = 99,
        ["gen_mediterranean_lowlands_02"] = 100,
        ["gen_mediterranean_lowlands_03"] = 101,
        ["gen_mediterranean_hills"] = 102,
        ["gen_mediterranean_mountain"] = 103,
        ["gen_mediterranean_mountain_transition"] = 104,
    };
}
