using Converter.Lemur;

namespace Converter.Lemur.Writers;

public static class StaticFilesWriter
{
    public static async Task Write(string tcsSandboxPath, string outputDirectory)
    {
        using var _ = OperationTimer.Start("Writing static files");
        var mapDataDir = Helper.GetPath(outputDirectory, "map_data");
        Directory.CreateDirectory(mapDataDir);

        await WriteTextFiles(mapDataDir);
        // Heightmap binaries (packed_heightmap.png, indirection_heightmap.png) and
        // heightmap.heightmap are now written by HeightmapWriter. No TCS copy needed.
    }

    private static async Task WriteTextFiles(string mapDataDir)
    {
        var enc = Helper.Utf8Bom;

        // seasons.txt — seasonal date ranges (same as vanilla/TCS)
        await File.WriteAllTextAsync(Helper.GetPath(mapDataDir, "seasons.txt"),
            "spring = {\n" +
            "\tstart = { month=2 day=15 }\n" +
            "\tend = { month=5 day=15 }\n" +
            "}\n" +
            "summer = {\n" +
            "\tstart = { month=5 day=15 }\n" +
            "\tend = { month=8 day=15 }\n" +
            "}\n" +
            "fall = {\n" +
            "\tstart = { month=8 day=15 }\n" +
            "\tend = { month=11 day=15 }\n" +
            "}\n" +
            "winter = {\n" +
            "\tstart = { month=11 day=15 }\n" +
            "\tend = { month=2 day=15 }\n" +
            "}\n", enc);

        // climate.txt — empty winter/summer climate blocks
        await File.WriteAllTextAsync(Helper.GetPath(mapDataDir, "climate.txt"),
            "mild_winter = {\n}\n" +
            "normal_winter = {\n}\n" +
            "severe_winter = {\n}\n", enc);

        // island_region.txt — no islands to declare
        await File.WriteAllTextAsync(Helper.GetPath(mapDataDir, "island_region.txt"), "", enc);

        // positions.txt — written EMPTY (0 bytes), matching TCS's own positions.txt.
        // Once we declare the map_data replace_path ourselves (TCS breakaway), there is no
        // fall-through: the file must exist or CK3 has no positions data at all. An empty file
        // makes CK3 default every map object to its province midpoint — which is exactly the
        // proven state today (TCS ships an empty positions.txt) and is independent of the modern
        // map_object_data locators we already emit via LocatorWriter. No BOM: byte-identical to TCS.
        await File.WriteAllTextAsync(Helper.GetPath(mapDataDir, "positions.txt"),
            "", new System.Text.UTF8Encoding(encoderShouldEmitUTF8Identifier: false));

        // heightmap.heightmap, packed_heightmap.png, and indirection_heightmap.png are
        // now generated by HeightmapWriter from Azgaar elevation data. StaticFilesWriter
        // no longer writes them.

        Logger.Info("Wrote static map_data text files (seasons, climate, island_region, empty positions)");
    }

}

